#if !defined(GEOMETRIX_DONT_USE_PREPROCESSED_FILES)
    #include <geometrix/tensor/detail/preprocessed/matrix.hpp>
#else
	#if !defined(BOOST_PP_IS_ITERATING)
	
	#include <boost\preprocessor\iteration\iterate.hpp>
    #include <boost\preprocessor\enum.hpp>
    #include <boost\preprocessor\enum_params.hpp>

		#if defined(__WAVE__) && defined(GEOMETRIX_CREATE_PREPROCESSED_FILES)
			#pragma wave option(preserve: 2, line: 0, output: "preprocessed/matrix.hpp")
		#endif
//
//! Copyright © 2008-2011
//! Brandon Kohn
//
//  Distributed under the Boost Software License, Version 1.0. (See
//  accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//
//! NOTE: This file is automatically generated. Any CHANGES made to this
//! file will be LOST on the next generation.
		#if defined(__WAVE__) && defined(GEOMETRIX_CREATE_PREPROCESSED_FILES)
			#pragma wave option(preserve: 1)
		#endif

    #define BOOST_PP_FILENAME_1 <geometrix/tensor/detail/matrix_m.hpp>
    #define BOOST_PP_ITERATION_LIMITS (1, GEOMETRIX_MAX_MATRIX_ROWS)
    #include BOOST_PP_ITERATE()

    #if defined(__WAVE__) && defined(GEOMETRIX_CREATE_PREPROCESSED_FILES)
        #pragma wave option(output: null)
    #endif

	#endif
#endif
