//
//! Copyright © 2008-2009
//! Brandon Kohn
//
//  Distributed under the Boost Software License, Version 1.0. (See
//  accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//

namespace generative
{
namespace numeric
{
namespace geometry
{

#define DIMENSION BOOST_PP_ITERATION()

/////////////////////////////////////////////////////////////////////////////
//
// CLASS point
//! A template class for specifying point which can be compile time
//! and runtime indexed conforming to random access for both and can support
//! vector arithmetic.
//!
template <typename NumericType>
class point<NumericType, DIMENSION>
    : public numeric_sequence< NumericType, DIMENSION >        
    , boost::additive< point<NumericType, DIMENSION>, vector< NumericType, DIMENSION >     // point +- numeric_sequence
    >
{
public:

    typedef numeric_sequence< NumericType, DIMENSION > sequence_type;
    typedef typename sequence_type::numeric_type       coordinate_type;

    point(){}

    //! define the constructors via the preprocessor.
    point( BOOST_PP_ENUM_PARAMS(DIMENSION, const numeric_type& a) )
        : sequence_type( BOOST_PP_ENUM_PARAMS(DIMENSION, a) )
    {
    }

    template <typename NumericSequence>
    point( const NumericSequence& a )
        : sequence_type( a )
    {}

    //! Operator interface    
    point operator+= ( const sequence_type& p )
    {
        sequence_type::operator +=( p );
        return *this;
    }

    // numeric_sequence operator+(numeric_sequence, const numeric_sequence&) automatically
    // generated by addable.

    point operator-= ( const sequence_type& p )
    {
        sequence_type::operator -=( p );
        return *this;
    }
    // numeric_sequence operator-(numeric_sequence, const numeric_sequence&) automatically
    // generated by subtractable.

};

//! Helper macro to build access traits code.
#define GENERATIVE_GEOMETRY_INDEXED_ACCESS_ARG_POINT_( z, i, T )         \
generative::numeric::geometry::indexed_access_traits< T >::get<i>( args )\
/***/

template <typename N>
struct construction_traits< point<N, DIMENSION> >
{    
    static point<N, DIMENSION> construct( BOOST_PP_ENUM_PARAMS(DIMENSION, const N& a) )
    {
        return point<N, DIMENSION>( BOOST_PP_ENUM_PARAMS(DIMENSION, a) );
    }
    
    template <typename NumericSequence>                                                                         
    static point<N,DIMENSION> construct( const NumericSequence& args )                                                    
    {                                                                                                           
        boost::function_requires< CompileTimeIndexedAccessConcept< NumericSequence > >();                       
        return point<N, DIMENSION>( BOOST_PP_ENUM( DIMENSION, GENERATIVE_GEOMETRY_INDEXED_ACCESS_ARG_POINT_, NumericSequence ) );
    }                                                                                                       
};

#undef GENERATIVE_GEOMETRY_INDEXED_ACCESS_ARG_POINT_
          
}}}//namespace generative::numeric::geometry

#undef DIMENSION
