//
//!  Copyright (c) 2008
//!  Brandon Kohn
//
//  Distributed under the Boost Software License, Version 1.0. (See
//  accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)
//

namespace boost
{
namespace numeric
{
namespace geometry
{

#define DIMENSION BOOST_PP_ITERATION()

/////////////////////////////////////////////////////////////////////////////
//
// CLASS sphere
//! A template class for specifying sphere which can be compile time
//! and runtime indexed conforming to random access for both and can support
//! vector and scalar arithmetic.
//!
template <typename NumericType>
class sphere<NumericType, DIMENSION>
    : public numeric_sequence< NumericType, DIMENSION >        
    , boost::additive< sphere<NumericType, DIMENSION>, vector< NumericType, DIMENSION >     // sphere +- numeric_sequence
    >
{
public:

    typedef numeric_sequence< NumericType, DIMENSION > sequence_type;
    typedef typename sequence_type::numeric_type       coordinate_type;

    sphere(){}

    //! define the constructors via the preprocessor.
    sphere( const numeric_type& radius, BOOST_PP_ENUM_PARAMS(DIMENSION, const numeric_type& a) )
        : sequence_type( BOOST_PP_ENUM_PARAMS(DIMENSION, a) )
        , m_radius( radius )
    {
    }

    sphere( const numeric_type& radius, const typename sequence_type::numeric_array& a )
        : sequence_type( a )
        , m_radius( radius )
    {}

    //! Operator interface    
    sphere operator+= ( const sequence_type& p )
    {
        sequence_type::operator +=( p );
        return *this;
    }

    // numeric_sequence operator+(numeric_sequence, const numeric_sequence&) automatically
    // generated by addable.

    sphere operator-= ( const sequence_type& p )
    {
        sequence_type::operator -=( p );
        return *this;
    }
    // numeric_sequence operator-(numeric_sequence, const numeric_sequence&) automatically
    // generated by subtractable.

};

template <typename N>
struct construction_traits< sphere< N, DIMENSION> >
{    
    static inline sphere<N, DIMENSION> construct( const N& radius, BOOST_PP_ENUM_PARAMS(DIMENSION, const N& a) )
    {
        return sphere<N, DIMENSION>( radius, BOOST_PP_ENUM_PARAMS(DIMENSION, a) );
    }

    template <typename NumericSequence>
    static inline sphere< N, DIMENSION> construct( const N& radius, const NumericSequence& args )
    {
        return sphere<N, DIMENSION>( radius, args );
    }
};
          
}}}//namespace boost::numeric::geometry

#undef DIMENSION
